### ISSUE TITLE
[CRAB-96] 세부 디테일 고치기

### ISSUE THREAD

**Issue by dydals3440** [crabit-official/Crabit-FE2#228]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!
[CRAB-96] 1차 출시 관련 QA 

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!
- [x] 챌린지 인증 게시글 (파일 뷰어 제거) 이미지만 일단 보이게 설정. 
- [x] 구글 로그인 제거 (추후 출시시 도입) 
- [x] 약관 화면 구현
- [x] 파일 뷰어 추가

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!
[CRAB-96] 세부 디테일 고치기

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)
- 챌린지 인증 게시글 (파일 뷰어 제거) 이미지만 일단 보이게 설정.
<img width="1096" alt="스크린샷 2024-12-05 오후 11 22 49" src="https://github.com/user-attachments/assets/5eb928a7-1e9d-45d0-87b9-5943620d4ae0">

- 구글 로그인 제거 (추후 출시시 도입) 
<img width="1071" alt="스크린샷 2024-12-05 오후 11 35 05" src="https://github.com/user-attachments/assets/83ac9447-619d-4a23-9312-cb5f6a60eef3">

-  파일 뷰어 추가
<img width="845" alt="스크린샷 2024-12-06 오후 1 55 59" src="https://github.com/user-attachments/assets/68cdaf71-c478-449f-9aee-24e6db3ad8c2">

[CRAB-96]: https://craftyourhabit.atlassian.net/browse/CRAB-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRAB-96]: https://craftyourhabit.atlassian.net/browse/CRAB-96?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by hijjoy** [comment]
- 첨부파일이 이미지 인경우는 보여야할 것 같습니다.........! 위에 토글에 있는 이미지는 첨부파일 이미지가 아니라 챌린지 생성시 올리는 이미지라서
