### ISSUE TITLE
[CRAB-33] 대시보드 페이지 ui 수정 

### ISSUE THREAD

**Issue by hijjoy** [crabit-official/Crabit-FE2#73]
## 👀 어떤 기능을 추가할 것인가요?
> 추가하려는 기능에 대해 설명해주세요!

## 🍀 기능을 추가하기 위해 어떤 작업이 진행될 것인가요?
> 기능을 추가하는 과정에서 진행될 작업에 대해 간략히 설명해주세요!

- [x] 대시보드 페이지 ui 수정 
- [x] 챌린지 마켓 ui 수정
- [x] 챌린지 마켓 모달 수정 
- [ ] 로그인 쿠키 수정

## ☕️ 어떤 브랜치에서 작업이 진행될까요?
> 해당 기능이 개발될 브랜치 명을 알려주세요!

CRAB-33-feature/#33

## 📒 이해를 돕기 위한 참고 자료 및 스크린샷을 첨부해주세요. (선택사항)

**Comment by dydals3440** [comment]
그녀는 그렇게 쿠키를 먹지 못했다고 한다..
